import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Inter, Roboto, Poppins } from "next/font/google";
import Footer from "@/components/footer/Footer";
import { ThemeProvider } from "@/context/ThemeContext";
import AuthProvider from "@/components/AuthProvider/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tulga ",
  description: "This is the description",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <div className="container">
              <Navbar />
              {children}
              <Footer />
            </div>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}





// Тайлбар:

// Код нь төслийн лавлах болон шаардлагатай CSS файлаас шаардлагатай бүрэлдэхүүн хэсгүүдийг импортолдог.
// Энэ нь мөн "next/font/google" багцаас фонт, тухайлбал Inter, Roboto, Poppins фонтуудыг импортолдог.
// Импортын багцаас Inter функцийг дуудаж, ["latin"] гэж тохируулсан "дэд олонлогууд" шинж чанартай объектыг дамжуулснаар "inter" тогтмолыг үүсгэдэг бөгөөд энэ нь фонтыг латин үсгээр хязгаарладаг.
// "Мета өгөгдөл" объект нь SEO зорилгоор ашиглаж болох гарчиг, тайлбарын шинж чанаруудыг агуулдаг.
// Өгөгдмөл экспорт нь "RootLayout" нэртэй функц бөгөөд "хүүхдүүд" тулгуурыг авдаг бөгөөд энэ нь байршлын бүрэлдэхүүн хэсэг дотор үзүүлэх агуулгыг илэрхийлдэг.
// Функцийн дотор HTML lang шинж чанарыг "html" таг ашиглан "en" гэж тохируулсан.
// Биеийн шошго нь "inter.className"-ийн утгад тохируулагдсан "className" атрибуттай бөгөөд энэ нь Inter үсгийн импортоор үүсгэгдсэн CSS анги юм.
// ThemeProvider бүрэлдэхүүн хэсэг нь түүний дотор хийгдсэн бүх бүрэлдэхүүн хэсгүүдэд сэдэвчилсэн контекстийг өгөхөд ашиглагддаг.
// AuthProvider бүрэлдэхүүн хэсэг нь түүний дотор хийгдсэн бүх бүрэлдэхүүн хэсгүүдэд баталгаажуулалттай холбоотой контекстийг хангахад ашиглагддаг.
// ClassName "контейнер"-тэй div дотор Navbar-ийн бүрэлдэхүүн хэсэг, дараа нь хуудасны үндсэн агуулгыг илэрхийлдэг "хүүхдүүд" тулгуур, эцэст нь Footer бүрэлдэхүүн хэсэгтэй байна.




// Explanation:

// The code imports the necessary components from the project directory and the required CSS file.
// It also imports fonts from the "next/font/google" package, specifically Inter, Roboto, and Poppins fonts.
// The "inter" constant is created by calling the Inter function from the imported package and passing an object with the "subsets" property set to ["latin"], which limits the font to Latin characters.
// The "metadata" object contains title and description properties that can be used for SEO purposes.
// The default export is a function named "RootLayout" that takes a "children" prop, which represents the content to be rendered within this layout component.
// Inside the function, the HTML lang attribute is set to "en" using the "html" tag.
// The body tag has a "className" attribute that is set to the value of "inter.className", which is a CSS class generated by the Inter font import.
// The ThemeProvider component is used to provide a theme context to all the components rendered within it.
// The AuthProvider component is used to provide authentication-related context to all the components rendered within it.
// Inside the div with the className "container", the Navbar component is rendered followed by the "children" prop, which represents the main content of the page, and finally the Footer component.